version: 2
jobs: # a basic unit of work in a run
  build: # runs not using `Workflows` must have a `build` job as entry poin
    docker: # Specifies the primary container image,
     # see circleci.com/docs/2.0/circleci-images/ for
     # the list of pre-built CircleCI images on dockerhub.
       - image: circleci/node:chakracore-10.13
         environment:
            BINARY: cli-kintone
    working_directory: ~/build_tmp
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: |
          VERSION=$CIRCLE_TAG
          if [ -z "$CIRCLE_TAG" ]; then VERSION="$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)"; fi
          echo "VERSION=$VERSION"
          echo "export VERSION=$VERSION" >> $BASH_ENV
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run build tsc to es6
          command: |
            npm run build
      - run:
          name: Compile nodejs to binaries
          command: |
            npm run package:all
      
      - run: |
          ARCHIVE_NAME="$BINARY-$VERSION-$CIRCLE_JOB.tar.gz"
          echo "ARCHIVE_NAME=$ARCHIVE_NAME"
          echo "export ARCHIVE_NAME=$ARCHIVE_NAME" >> $BASH_ENV
      - run: |
          ARCHIVE_PATH="build/$ARCHIVE_NAME"
          echo "ARCHIVE_PATH=$ARCHIVE_PATH"
          echo "export ARCHIVE_PATH=$ARCHIVE_PATH" >> $BASH_ENV
      
      - run: tar -czvf "$ARCHIVE_PATH" -C "build" .
      - store_artifacts:
          path: build/
          destination: build/*
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: build
          # Must be relative path from root
          paths:
            - $ARCHIVE_NAME
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /build_tmp/build
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=0.1.0
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} build_tmp/build/*
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/